### ISSUE TITLE
update ngspice

### ISSUE THREAD

**Issue by adamwolf** [KiCad/kicad-mac-builder#257]
@nickoe made a PR #256 for updating to the latest ngspice tag.  It didn't work, and fails with:

``
03:08:47     default: [ 57%] Building CXX object eeschema/CMakeFiles/eeschema_kiface.dir/sim/ngspice.cpp.o
03:08:48     default: In file included from /vagrant/build/kicad/src/kicad/eeschema/sim/ngspice.cpp:28:
03:08:48     default: /vagrant/build/kicad/src/kicad/eeschema/sim/ngspice.h:31:10: fatal error: 'ngspice/sharedspice.h' file not found
03:08:48     default: #include <ngspice/sharedspice.h>
03:08:48     default:          ^
03:08:49     default: 1 error generated.
03:08:49     default: make[6]: *** [eeschema/CMakeFiles/eeschema_kiface.dir/sim/ngspice.cpp.o] Error 1
``

Let's fix this.

**Comment by nickoe** [comment]
Where is the full log?

**Comment by adamwolf** [comment]
@nickoe I tried updating ngspice again.  Here's the log.

https://builder.wayneandlayne.com/job/kicad-mac-builder-10.14-upload/249/consoleFull

**Comment by nickoe** [comment]
This is the error:
```
[ 53%] Building CXX object eeschema/CMakeFiles/eeschema_kiface_objects.dir/sim/ngspice.cpp.o
In file included from /vagrant/build/kicad/src/kicad/eeschema/sim/ngspice.cpp:28:
/vagrant/build/kicad/src/kicad/eeschema/sim/ngspice.h:31:10: fatal error: 'ngspice/sharedspice.h' file not found
#include <ngspice/sharedspice.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

```

**Comment by adamwolf** [comment]
Yeah... that didn't happen with ngspice 28.  I'm going to revert it but
keep it building on a branch.  I am not able to put more effort into the
ngspice stuff at this time but maybe someone else can do PRs then.

**Comment by adamwolf** [comment]
The job will be at https://builder.wayneandlayne.com/job/kicad-mac-builder-10.14-ngspice-upload/

**Comment by adamwolf** [comment]
Alright, the job built, here: https://builder.wayneandlayne.com/job/kicad-mac-builder-10.14-ngspice-upload/1/consoleFull

**Comment by adamwolf** [comment]
nickoe, the build is on a completely brand new VM every single time.  I'll try changing the include path.  Thanks for the sleuthing.

**Comment by adamwolf** [comment]
I got it working on my dev machine.  Pushed to the branch, we 'll see what happens overnight.

**Comment by nickoe** [comment]
@adamwolf Could you check your build nodes? The builds have been running for 1 day and 15 hours by now. Maybe the build script is running too many things in parralel and using all the machine memory?

**Comment by adamwolf** [comment]
I'll take a look. Thanks Nick.  I was trying to get the build machines to
also have build a new template 10.15 Beta VM so it's likely I was just
optimistic...

**Comment by nickoe** [comment]
@adamwolf ok, the build did became green!!!! woo

https://builder.wayneandlayne.com/job/kicad-mac-builder-10.14-ngspice-upload/10/

I guess we can merge https://github.com/KiCad/kicad-mac-builder/pull/286

**Comment by adamwolf** [comment]
Thanks nick and everyone for your patience!

**Comment by nickoe** [comment]
@adamwolf Maybe you should delete the ngspice-upload build and re-enable https://builder.wayneandlayne.com/job/kicad-mac-builder-10.14-upload/  ?

**Comment by adamwolf** [comment]
Done!
